# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='castInPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_description', models.CharField(max_length=255)),
                ('panel_quantity', models.PositiveSmallIntegerField()),
                ('panel_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panel_length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panel_height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panel_contact_area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wall_area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wall_type', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='footings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footing_description', models.CharField(max_length=255)),
                ('footing_type', models.CharField(max_length=255)),
                ('footing_width', models.PositiveSmallIntegerField()),
                ('footing_depth', models.PositiveSmallIntegerField()),
                ('footing_length', models.PositiveSmallIntegerField()),
                ('footing_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('footing_concrete_mix', models.CharField(max_length=255)),
                ('footing_concrete_grout', models.CharField(max_length=255)),
                ('footing_lumber', models.CharField(max_length=255)),
                ('footing_misc_materials', models.CharField(max_length=255)),
                ('footing_subcontractor', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_conditions_description', models.CharField(max_length=255)),
                ('general_conditions_cost', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='mixDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concrete_mix_description', models.CharField(max_length=255)),
                ('concrete_mix_psi', models.PositiveSmallIntegerField()),
                ('concrete_mix_price', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='openBudgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.PositiveIntegerField(unique=True)),
                ('zip_code', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('internal_due_date', models.DateField()),
                ('external_due_date', models.DateField()),
                ('estimator', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('budget_complete', models.CharField(choices=[('In Progress', 'In Progress'), ('Ready For Review', 'Ready To Review'), ('Reviewed', 'Reviewed'), ('Complete', 'Completed')], default='In Progress', max_length=20)),
                ('tax_exempt_status', models.BooleanField()),
                ('revised_date', models.DateField(auto_now=True)),
                ('general_contractor', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-budget_id'],
            },
        ),
        migrations.CreateModel(
            name='slabOnDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_on_deck_type', models.CharField(max_length=255)),
                ('slab_on_deck_description', models.CharField(max_length=255)),
                ('slab_on_deck_thickness', models.DecimalField(decimal_places=4, max_digits=25)),
                ('slab_on_deck_area', models.DecimalField(decimal_places=4, max_digits=25)),
                ('slab_on_deck_forms', models.DecimalField(decimal_places=4, max_digits=25)),
                ('slab_on_deck_concrete_mix', models.CharField(max_length=255)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='slabOnGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sog_slab_description', models.CharField(max_length=255)),
                ('sog_grading_material_thickness', models.PositiveSmallIntegerField()),
                ('sog_thickness', models.PositiveSmallIntegerField()),
                ('sog_width', models.PositiveSmallIntegerField()),
                ('sog_length', models.PositiveSmallIntegerField()),
                ('sog_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sog_perimeter', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sog_concrete_mix', models.CharField(max_length=60)),
                ('sog_additive', models.CharField(max_length=100)),
                ('sog_second_additive', models.CharField(max_length=100)),
                ('sog_cure', models.CharField(max_length=100)),
                ('sog_perimeter_forms', models.CharField(max_length=100)),
                ('sog_bulk_heads', models.CharField(max_length=100)),
                ('sog_vapor_barrier', models.CharField(max_length=100)),
                ('sog_grading_material', models.CharField(max_length=100)),
                ('sog_anchor_bolts', models.CharField(max_length=100)),
                ('sog_subcontractor_first', models.CharField(max_length=100)),
                ('sog_subcontractor_second', models.CharField(max_length=100)),
                ('sog_subcontractor_third', models.CharField(max_length=100)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tiltUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilt_up_panel_description', models.CharField(max_length=255)),
                ('tilt_up_panel_thickness', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_width', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_height', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_forms', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_perimeter', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_gross_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_openings_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_net_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_weight', models.PositiveSmallIntegerField()),
                ('tilt_up_panel_concrete_mix', models.CharField(max_length=150)),
                ('tilt_up_panel_additive', models.CharField(max_length=100)),
                ('tilt_up_panel_second_additive', models.CharField(max_length=100)),
                ('tilt_up_panel_forms', models.CharField(max_length=100)),
                ('tilt_up_panel_engineering', models.CharField(max_length=100)),
                ('tilt_up_panel_crane', models.CharField(max_length=100)),
                ('tilt_up_panel_caulking', models.CharField(max_length=100)),
                ('tilt_up_panel_pumping', models.CharField(max_length=100)),
                ('tilt_up_panel_welding', models.CharField(max_length=100)),
                ('tilt_up_sack_patch', models.CharField(max_length=100)),
                ('tilt_up_brace_rental', models.CharField(max_length=100)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_casting_description', models.CharField(max_length=255)),
                ('waste_casting_basis', models.CharField(max_length=255)),
                ('waste_casting_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('waste_casting_concrete_description', models.CharField(max_length=255)),
                ('waste_casting_totalCY', models.PositiveSmallIntegerField()),
                ('waste_casting_psi', models.PositiveSmallIntegerField()),
                ('waste_casting_materials_labor', models.CharField(max_length=255)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets')),
            ],
        ),
        migrations.AddField(
            model_name='generalconditions',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
        ),
        migrations.AddField(
            model_name='footings',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
        ),
        migrations.AddField(
            model_name='castinplace',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
        ),
    ]
