# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='awardedBudgets',
            fields=[
                ('budget_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('internal_due_date', models.DateField()),
                ('external_due_date', models.DateField()),
                ('estimator', models.CharField(max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('budget_complete', models.CharField(choices=[(b'IP', b'In Progress'), (b'RTR', b'Ready To Review'), (b'RV', b'Reviewed'), (b'CMP', b'Completed')], default=b'IP', max_length=3)),
                ('revised_date', models.DateField()),
                ('tax_exempt_status', models.CharField(choices=[(b'*', b'*'), (b'', b'')], default=b'', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='castInPlace',
            fields=[
                ('panel_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('panel_description', models.CharField(max_length=255)),
                ('panel_quantity', models.PositiveSmallIntegerField()),
                ('panel_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panel_length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panel_height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panel_contact_area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wall_area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wall_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='closedBudgets',
            fields=[
                ('budget_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('internal_due_date', models.DateField()),
                ('external_due_date', models.DateField()),
                ('estimator', models.CharField(max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('budget_complete', models.CharField(choices=[(b'IP', b'In Progress'), (b'RTR', b'Ready To Review'), (b'RV', b'Reviewed'), (b'CMP', b'Completed')], default=b'IP', max_length=3)),
                ('revised_date', models.DateField()),
                ('tax_exempt_status', models.CharField(choices=[(b'*', b'*'), (b'', b'')], default=b'', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='footings',
            fields=[
                ('footing_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fooding_description', models.CharField(max_length=255)),
                ('footing_type', models.CharField(max_length=255)),
                ('footing_width', models.PositiveSmallIntegerField()),
                ('footing_depth', models.PositiveSmallIntegerField()),
                ('footing_length', models.PositiveSmallIntegerField()),
                ('footing_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('footing_concrete_mix', models.CharField(max_length=255)),
                ('footing_concrete_grout', models.CharField(max_length=255)),
                ('footing_lumber', models.CharField(max_length=255)),
                ('footing_misc_materials', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mixDesign',
            fields=[
                ('concrete_mix_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('concrete_mix_description', models.CharField(max_length=255)),
                ('concrete_mix_psi', models.PositiveSmallIntegerField()),
                ('concrete_mix_price', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='openBudgets',
            fields=[
                ('budget_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('internal_due_date', models.DateField()),
                ('external_due_date', models.DateField()),
                ('estimator', models.CharField(max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('budget_complete', models.CharField(choices=[(b'IP', b'In Progress'), (b'RTR', b'Ready To Review'), (b'RV', b'Reviewed'), (b'CMP', b'Completed')], default=b'IP', max_length=3)),
                ('revised_date', models.DateField()),
                ('tax_exempt_status', models.CharField(choices=[(b'*', b'*'), (b'', b'')], default=b'', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pendingBudgets',
            fields=[
                ('budget_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('internal_due_date', models.DateField()),
                ('external_due_date', models.DateField()),
                ('estimator', models.CharField(max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('budget_complete', models.CharField(choices=[(b'IP', b'In Progress'), (b'RTR', b'Ready To Review'), (b'RV', b'Reviewed'), (b'CMP', b'Completed')], default=b'IP', max_length=3)),
                ('revised_date', models.DateField()),
                ('tax_exempt_status', models.CharField(choices=[(b'*', b'*'), (b'', b'')], default=b'', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='slabOnGrade',
            fields=[
                ('sog_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('sog_grading_material_thickness', models.PositiveSmallIntegerField()),
                ('sog_thickness', models.PositiveSmallIntegerField()),
                ('sog_width', models.PositiveSmallIntegerField()),
                ('sog_length', models.PositiveSmallIntegerField()),
                ('sog_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sog_perimeter', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sog_concrete_mix', models.CharField(max_length=60)),
                ('sog_additive', models.CharField(max_length=100)),
                ('sog_second_additive', models.CharField(max_length=100)),
                ('sog_cure', models.CharField(max_length=100)),
                ('sog_perimeter_forms', models.CharField(max_length=100)),
                ('sog_bulk_heads', models.CharField(max_length=100)),
                ('sog_vapor_barrier', models.CharField(max_length=100)),
                ('sog_grading_material', models.CharField(max_length=100)),
                ('sog_anchor_bolts', models.CharField(max_length=100)),
                ('sog_subcontractor_first', models.CharField(max_length=100)),
                ('sog_subcontractor_second', models.CharField(max_length=100)),
                ('sog_subcontractor_third', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tiltUp',
            fields=[
                ('titl_up_panel_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tilt_up_panel_description', models.CharField(max_length=255)),
                ('tilt_up_panel_thickness', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_width', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_height', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_forms', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_perimeter', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_gross_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_openings_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_net_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tilt_up_panel_weight', models.PositiveSmallIntegerField()),
                ('tilt_up_panel_concrete_mix', models.CharField(max_length=150)),
                ('tilt_up_panel_additive', models.CharField(max_length=100)),
                ('tilt_up_panel_second_additive', models.CharField(max_length=100)),
                ('tilt_up_panel_forms', models.CharField(max_length=100)),
                ('tilt_up_panel_engineering', models.CharField(max_length=100)),
                ('tilt_up_panel_crane', models.CharField(max_length=100)),
                ('tilt_up_panel_caulking', models.CharField(max_length=100)),
                ('tilt_up_panel_pumping', models.CharField(max_length=100)),
                ('tilt_up_panel_welding', models.CharField(max_length=100)),
                ('tilt_up_sack_patch', models.CharField(max_length=100)),
                ('tilt_up_brace_rental', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='castinplace',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
        ),
    ]
