# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconditions',
            name='general_conditions_budget_code',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
