# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openbudgets',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='openbudgets',
            name='revised_date',
            field=models.DateField(auto_now=True),
        ),
    ]
