# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardedbudgets',
            name='budget_complete',
            field=models.CharField(choices=[('IP', 'In Progress'), ('RTR', 'Ready To Review'), ('RV', 'Reviewed'), ('CMP', 'Completed')], default='IP', max_length=3),
        ),
        migrations.AlterField(
            model_name='awardedbudgets',
            name='tax_exempt_status',
            field=models.CharField(choices=[('*', '*'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='closedbudgets',
            name='budget_complete',
            field=models.CharField(choices=[('IP', 'In Progress'), ('RTR', 'Ready To Review'), ('RV', 'Reviewed'), ('CMP', 'Completed')], default='IP', max_length=3),
        ),
        migrations.AlterField(
            model_name='closedbudgets',
            name='tax_exempt_status',
            field=models.CharField(choices=[('*', '*'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='openbudgets',
            name='budget_complete',
            field=models.CharField(choices=[('IP', 'In Progress'), ('RTR', 'Ready To Review'), ('RV', 'Reviewed'), ('CMP', 'Completed')], default='IP', max_length=3),
        ),
        migrations.AlterField(
            model_name='openbudgets',
            name='tax_exempt_status',
            field=models.CharField(choices=[('*', '*'), ('', '')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='pendingbudgets',
            name='budget_complete',
            field=models.CharField(choices=[('IP', 'In Progress'), ('RTR', 'Ready To Review'), ('RV', 'Reviewed'), ('CMP', 'Completed')], default='IP', max_length=3),
        ),
        migrations.AlterField(
            model_name='pendingbudgets',
            name='tax_exempt_status',
            field=models.CharField(choices=[('*', '*'), ('', '')], default='', max_length=1),
        ),
    ]
