# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_generalconditions_general_conditions_budget_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconditions',
            name='general_conditions_description',
            field=models.TextField(),
        ),
    ]
