# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20171117_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbudgets',
            name='general_contractor',
            field=models.CharField(default='Default General Contractor', max_length=50),
            preserve_default=False,
        ),
    ]
