# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_openbudgets_general_contractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openbudgets',
            options={'ordering': ['-budget_id']},
        ),
    ]
