# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20171121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='castinplace',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footings',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slabondeck',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slabongrade',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiltup',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
    ]
