# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20171122_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_conditions_description', models.CharField(max_length=255)),
                ('general_conditions_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets')),
            ],
        ),
        migrations.AddField(
            model_name='castinplace',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footings',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slabondeck',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slabongrade',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiltup',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets'),
            preserve_default=False,
        ),
    ]
