# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_auto_20171122_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_casting_description', models.CharField(max_length=255)),
                ('waste_casting_basis', models.CharField(max_length=255)),
                ('waste_casting_sqft', models.DecimalField(decimal_places=4, max_digits=15)),
                ('waste_casting_concrete_description', models.CharField(max_length=255)),
                ('waste_casting_totalCY', models.PositiveSmallIntegerField()),
                ('waste_casting_psi', models.PositiveSmallIntegerField()),
                ('waste_casting_materials_labor', models.CharField(max_length=255)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.openBudgets')),
            ],
        ),
    ]
